# Generated by Django 2.1.7 on 2019-05-12 02:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user_clove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
        migrations.AddField(
            model_name='course',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(verbose_name='課程代碼'),
        ),
    ]
